### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by suho** [y4gamilight/nimble-assignment#52]
Hello Thanh 👋 , thank you for your effort on the code submission. I am Su, currently Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

**Comment by suho** [comment]
Hi @y4gamilight, I just completed my review, please provide your feedback on my open issues.

Please note that you don't need to make any changes or commit any code. Just discuss directly on my open issues :pray:

**Comment by y4gamilight** [comment]
Thank you so much I will check now

**Comment by y4gamilight** [comment]
@suho, thank you for your feedback. I have provided comments on all of your issues. I hope to improve my assignment. If you have any concerns about my answers or new feedback, I am always ready to share my opinions and reasons

**Comment by suho** [comment]
Hi @y4gamilight, I've checked all your comments. Thanks for your reply.

As of this point, this code challenge review session has concluded. For the next step, you will hear from the Talent Acquisition team about the decision as soon as it is available. Thanks for your time, and I wish you all the best! 🍀

**Comment by y4gamilight** [comment]
Hi @suho, thank you for taking the time to review my code.
I wasn't satisfied with my assignment, but I hope to receive good news from the TA teams.
Have a nice day!
